### ISSUE TITLE
Can't upload sketch on Ubuntu 17.04 or macOS 10.12.6

### ISSUE THREAD

**Issue by zezba9000** [sifive/cinco#26]
I get the same error on Linux and Mac when I try to upload the blink sketch. Im using Arduino IDE 1.8.5. Is there only a specific version supported?

> Build options changed, rebuilding all
> Sketch uses 7814 bytes (0%) of program storage space. Maximum is 8388608 bytes.
> java.lang.NullPointerException
> 	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingProgrammer(SerialUploader.java:314)
> 	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:89)
> 	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
> 	at processing.app.SketchController.upload(SketchController.java:713)
> 	at processing.app.SketchController.exportApplet(SketchController.java:686)
> 	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2168)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by zhaofengli** [comment]
You may have forgotten to select "SiFive OpenOCD" as the programmer.
